version: '3.8'

services:
    # NestJS API service
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        env_file:
            - ./env/.env
            - ./env/.env.${NODE_ENV}
        environment:
            NODE_ENV: ${NODE_ENV:-dev}
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules

        command: >
            sh -c "
              npx prisma migrate deploy &&
              npm run start:${NODE_ENV}
            "

    # PostgreSQL service
    postgres:
        image: postgres:13
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-user}']
            interval: 10s
            timeout: 5s
            retries: 5

    # Adminer (Database Management Interface) for development ease
    adminer:
        image: adminer
        restart: always
        ports:
            - '8080:8080'
        depends_on:
            - postgres

volumes:
    postgres_data:
